baseurl      = "https://mattpetty.github.io"
title        = "Matt's Networking Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
rssLimit     = 10
publishDir   = "docs"

[permalinks]
  posts = '/:year/:month/:day/:title/'

[author]
  name            = "Matt Petty"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Set a background for the homepage
  # backgroundImage = "assets/images/background.jpg"

  # Subtitle for home
  homeSubtitle = "A tech-focused blog about networking, Python, and automation, for the modern-day struggling network engineer."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Dark Mode toggle button
  enableThemeToggle = true

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "Matt Petty's personal blog, with a focus on technical topics"
  keywords = "homepage, blog"
  images = [""]

  [params.logo]
    logoText     = "mattpetty.github.io"
    logoHomeLink = "/"
    # Configure for a custom prompt mark
    # logoMark     = ">"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = true
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"
    #
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [params.portrait]
    path     = "router_icon.png"
    alt      = "Router Icon"
    maxWidth = "150px"

  [params.footer]
    trademark = true
    rss = true
    copyright = false
    author = true

    topText = ["theme: <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">hello-friend-ng</a>"]
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>, <a href=\"https://pages.github.com\">GitHub Pages</a>, and lots of coffee"
    ]

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/mpetty1"

  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/mpetty7052/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/mattpetty"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/matt-petty-84221bb/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[menu]
  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
